/**
 * Wereldwijde landenlijst voor de ROUT-checkout (gegenereerd uit ISO 3166-1 +
 * ISO 4217). Isomorf: client (zoekbare selector) en server (valuta-routing)
 * gebruiken exact dezelfde tabel.
 */

export interface CountryEntry {
  /** ISO 3166-1 alpha-2. */
  code: string;
  /** ISO 4217-valuta van dat land. */
  currency: string;
  nl: string;
  en: string;
  fr: string;
  de: string;
}

export const COUNTRIES: CountryEntry[] = [
  { code: "AD", currency: "EUR", nl: "Andorra", en: "Andorra", fr: "Andorre", de: "Andorra" },
  { code: "AE", currency: "AED", nl: "Verenigde Arabische Emiraten", en: "United Arab Emirates", fr: "Émirats arabes unis", de: "Vereinigte Arabische Emirate" },
  { code: "AF", currency: "AFN", nl: "Afghanistan", en: "Afghanistan", fr: "Afghanistan", de: "Afghanistan" },
  { code: "AG", currency: "XCD", nl: "Antigua en Barbuda", en: "Antigua & Barbuda", fr: "Antigua-et-Barbuda", de: "Antigua und Barbuda" },
  { code: "AI", currency: "XCD", nl: "Anguilla", en: "Anguilla", fr: "Anguilla", de: "Anguilla" },
  { code: "AL", currency: "ALL", nl: "Albanië", en: "Albania", fr: "Albanie", de: "Albanien" },
  { code: "AM", currency: "AMD", nl: "Armenië", en: "Armenia", fr: "Arménie", de: "Armenien" },
  { code: "AN", currency: "ANG", nl: "Curaçao", en: "Curaçao", fr: "Curaçao", de: "Curaçao" },
  { code: "AO", currency: "AOA", nl: "Angola", en: "Angola", fr: "Angola", de: "Angola" },
  { code: "AQ", currency: "USD", nl: "Antarctica", en: "Antarctica", fr: "Antarctique", de: "Antarktis" },
  { code: "AR", currency: "ARS", nl: "Argentinië", en: "Argentina", fr: "Argentine", de: "Argentinien" },
  { code: "AS", currency: "USD", nl: "Amerikaans-Samoa", en: "American Samoa", fr: "Samoa américaines", de: "Amerikanisch-Samoa" },
  { code: "AT", currency: "EUR", nl: "Oostenrijk", en: "Austria", fr: "Autriche", de: "Österreich" },
  { code: "AU", currency: "AUD", nl: "Australië", en: "Australia", fr: "Australie", de: "Australien" },
  { code: "AW", currency: "AWG", nl: "Aruba", en: "Aruba", fr: "Aruba", de: "Aruba" },
  { code: "AX", currency: "EUR", nl: "Åland", en: "Åland Islands", fr: "Îles Åland", de: "Ålandinseln" },
  { code: "AZ", currency: "AZN", nl: "Azerbeidzjan", en: "Azerbaijan", fr: "Azerbaïdjan", de: "Aserbaidschan" },
  { code: "BA", currency: "BAM", nl: "Bosnië en Herzegovina", en: "Bosnia & Herzegovina", fr: "Bosnie-Herzégovine", de: "Bosnien und Herzegowina" },
  { code: "BB", currency: "BBD", nl: "Barbados", en: "Barbados", fr: "Barbade", de: "Barbados" },
  { code: "BD", currency: "BDT", nl: "Bangladesh", en: "Bangladesh", fr: "Bangladesh", de: "Bangladesch" },
  { code: "BE", currency: "EUR", nl: "België", en: "Belgium", fr: "Belgique", de: "Belgien" },
  { code: "BF", currency: "XOF", nl: "Burkina Faso", en: "Burkina Faso", fr: "Burkina Faso", de: "Burkina Faso" },
  { code: "BG", currency: "EUR", nl: "Bulgarije", en: "Bulgaria", fr: "Bulgarie", de: "Bulgarien" },
  { code: "BH", currency: "BHD", nl: "Bahrein", en: "Bahrain", fr: "Bahreïn", de: "Bahrain" },
  { code: "BI", currency: "BIF", nl: "Burundi", en: "Burundi", fr: "Burundi", de: "Burundi" },
  { code: "BJ", currency: "XOF", nl: "Benin", en: "Benin", fr: "Bénin", de: "Benin" },
  { code: "BL", currency: "EUR", nl: "Saint-Barthélemy", en: "St. Barthélemy", fr: "Saint-Barthélemy", de: "St. Barthélemy" },
  { code: "BM", currency: "BMD", nl: "Bermuda", en: "Bermuda", fr: "Bermudes", de: "Bermuda" },
  { code: "BN", currency: "BND", nl: "Brunei", en: "Brunei", fr: "Brunei", de: "Brunei Darussalam" },
  { code: "BO", currency: "BOB", nl: "Bolivia", en: "Bolivia", fr: "Bolivie", de: "Bolivien" },
  { code: "BQ", currency: "USD", nl: "Caribisch Nederland", en: "Caribbean Netherlands", fr: "Pays-Bas caribéens", de: "Karibische Niederlande" },
  { code: "BR", currency: "BRL", nl: "Brazilië", en: "Brazil", fr: "Brésil", de: "Brasilien" },
  { code: "BS", currency: "BSD", nl: "Bahama’s", en: "Bahamas", fr: "Bahamas", de: "Bahamas" },
  { code: "BT", currency: "BTN", nl: "Bhutan", en: "Bhutan", fr: "Bhoutan", de: "Bhutan" },
  { code: "BV", currency: "NOK", nl: "Bouveteiland", en: "Bouvet Island", fr: "Île Bouvet", de: "Bouvetinsel" },
  { code: "BW", currency: "BWP", nl: "Botswana", en: "Botswana", fr: "Botswana", de: "Botsuana" },
  { code: "BY", currency: "BYN", nl: "Belarus", en: "Belarus", fr: "Biélorussie", de: "Belarus" },
  { code: "BZ", currency: "BZD", nl: "Belize", en: "Belize", fr: "Belize", de: "Belize" },
  { code: "CA", currency: "CAD", nl: "Canada", en: "Canada", fr: "Canada", de: "Kanada" },
  { code: "CC", currency: "AUD", nl: "Cocoseilanden", en: "Cocos (Keeling) Islands", fr: "Îles Cocos", de: "Kokosinseln" },
  { code: "CD", currency: "CDF", nl: "Congo-Kinshasa", en: "Congo - Kinshasa", fr: "Congo-Kinshasa", de: "Kongo-Kinshasa" },
  { code: "CF", currency: "XAF", nl: "Centraal-Afrikaanse Republiek", en: "Central African Republic", fr: "République centrafricaine", de: "Zentralafrikanische Republik" },
  { code: "CG", currency: "XAF", nl: "Congo-Brazzaville", en: "Congo - Brazzaville", fr: "Congo-Brazzaville", de: "Kongo-Brazzaville" },
  { code: "CH", currency: "CHF", nl: "Zwitserland", en: "Switzerland", fr: "Suisse", de: "Schweiz" },
  { code: "CI", currency: "XOF", nl: "Ivoorkust", en: "Côte d’Ivoire", fr: "Côte d’Ivoire", de: "Côte d’Ivoire" },
  { code: "CK", currency: "NZD", nl: "Cookeilanden", en: "Cook Islands", fr: "Îles Cook", de: "Cookinseln" },
  { code: "CL", currency: "CLP", nl: "Chili", en: "Chile", fr: "Chili", de: "Chile" },
  { code: "CM", currency: "XAF", nl: "Kameroen", en: "Cameroon", fr: "Cameroun", de: "Kamerun" },
  { code: "CN", currency: "CNY", nl: "China", en: "China", fr: "Chine", de: "China" },
  { code: "CO", currency: "COP", nl: "Colombia", en: "Colombia", fr: "Colombie", de: "Kolumbien" },
  { code: "CR", currency: "CRC", nl: "Costa Rica", en: "Costa Rica", fr: "Costa Rica", de: "Costa Rica" },
  { code: "CU", currency: "CUP", nl: "Cuba", en: "Cuba", fr: "Cuba", de: "Kuba" },
  { code: "CV", currency: "CVE", nl: "Kaapverdië", en: "Cape Verde", fr: "Cap-Vert", de: "Cabo Verde" },
  { code: "CW", currency: "XCG", nl: "Curaçao", en: "Curaçao", fr: "Curaçao", de: "Curaçao" },
  { code: "CX", currency: "AUD", nl: "Christmaseiland", en: "Christmas Island", fr: "Île Christmas", de: "Weihnachtsinsel" },
  { code: "CY", currency: "EUR", nl: "Cyprus", en: "Cyprus", fr: "Chypre", de: "Zypern" },
  { code: "CZ", currency: "CZK", nl: "Tsjechië", en: "Czechia", fr: "Tchéquie", de: "Tschechien" },
  { code: "DE", currency: "EUR", nl: "Duitsland", en: "Germany", fr: "Allemagne", de: "Deutschland" },
  { code: "DJ", currency: "DJF", nl: "Djibouti", en: "Djibouti", fr: "Djibouti", de: "Dschibuti" },
  { code: "DK", currency: "DKK", nl: "Denemarken", en: "Denmark", fr: "Danemark", de: "Dänemark" },
  { code: "DM", currency: "XCD", nl: "Dominica", en: "Dominica", fr: "Dominique", de: "Dominica" },
  { code: "DO", currency: "DOP", nl: "Dominicaanse Republiek", en: "Dominican Republic", fr: "République dominicaine", de: "Dominikanische Republik" },
  { code: "DZ", currency: "DZD", nl: "Algerije", en: "Algeria", fr: "Algérie", de: "Algerien" },
  { code: "EC", currency: "USD", nl: "Ecuador", en: "Ecuador", fr: "Équateur", de: "Ecuador" },
  { code: "EE", currency: "EUR", nl: "Estland", en: "Estonia", fr: "Estonie", de: "Estland" },
  { code: "EG", currency: "EGP", nl: "Egypte", en: "Egypt", fr: "Égypte", de: "Ägypten" },
  { code: "EH", currency: "MAD", nl: "Westelijke Sahara", en: "Western Sahara", fr: "Sahara occidental", de: "Westsahara" },
  { code: "ER", currency: "ERN", nl: "Eritrea", en: "Eritrea", fr: "Érythrée", de: "Eritrea" },
  { code: "ES", currency: "EUR", nl: "Spanje", en: "Spain", fr: "Espagne", de: "Spanien" },
  { code: "ET", currency: "ETB", nl: "Ethiopië", en: "Ethiopia", fr: "Éthiopie", de: "Äthiopien" },
  { code: "FI", currency: "EUR", nl: "Finland", en: "Finland", fr: "Finlande", de: "Finnland" },
  { code: "FJ", currency: "FJD", nl: "Fiji", en: "Fiji", fr: "Fidji", de: "Fidschi" },
  { code: "FK", currency: "FKP", nl: "Falklandeilanden", en: "Falkland Islands", fr: "Îles Malouines", de: "Falklandinseln" },
  { code: "FM", currency: "USD", nl: "Micronesia", en: "Micronesia", fr: "Micronésie", de: "Mikronesien" },
  { code: "FO", currency: "DKK", nl: "Faeröer", en: "Faroe Islands", fr: "Îles Féroé", de: "Färöer" },
  { code: "FR", currency: "EUR", nl: "Frankrijk", en: "France", fr: "France", de: "Frankreich" },
  { code: "GA", currency: "XAF", nl: "Gabon", en: "Gabon", fr: "Gabon", de: "Gabun" },
  { code: "GB", currency: "GBP", nl: "Verenigd Koninkrijk", en: "United Kingdom", fr: "Royaume-Uni", de: "Vereinigtes Königreich" },
  { code: "GD", currency: "XCD", nl: "Grenada", en: "Grenada", fr: "Grenade", de: "Grenada" },
  { code: "GE", currency: "GEL", nl: "Georgië", en: "Georgia", fr: "Géorgie", de: "Georgien" },
  { code: "GF", currency: "EUR", nl: "Frans-Guyana", en: "French Guiana", fr: "Guyane française", de: "Französisch-Guayana" },
  { code: "GG", currency: "GBP", nl: "Guernsey", en: "Guernsey", fr: "Guernesey", de: "Guernsey" },
  { code: "GH", currency: "GHS", nl: "Ghana", en: "Ghana", fr: "Ghana", de: "Ghana" },
  { code: "GI", currency: "GIP", nl: "Gibraltar", en: "Gibraltar", fr: "Gibraltar", de: "Gibraltar" },
  { code: "GL", currency: "DKK", nl: "Groenland", en: "Greenland", fr: "Groenland", de: "Grönland" },
  { code: "GM", currency: "GMD", nl: "Gambia", en: "Gambia", fr: "Gambie", de: "Gambia" },
  { code: "GN", currency: "GNF", nl: "Guinee", en: "Guinea", fr: "Guinée", de: "Guinea" },
  { code: "GP", currency: "EUR", nl: "Guadeloupe", en: "Guadeloupe", fr: "Guadeloupe", de: "Guadeloupe" },
  { code: "GQ", currency: "XAF", nl: "Equatoriaal-Guinea", en: "Equatorial Guinea", fr: "Guinée équatoriale", de: "Äquatorialguinea" },
  { code: "GR", currency: "EUR", nl: "Griekenland", en: "Greece", fr: "Grèce", de: "Griechenland" },
  { code: "GS", currency: "FKP", nl: "Zuid-Georgia en Zuidelijke Sandwicheilanden", en: "South Georgia & South Sandwich Islands", fr: "Géorgie du Sud-et-les Îles Sandwich du Sud", de: "Südgeorgien und die Südlichen Sandwichinseln" },
  { code: "GT", currency: "GTQ", nl: "Guatemala", en: "Guatemala", fr: "Guatemala", de: "Guatemala" },
  { code: "GU", currency: "USD", nl: "Guam", en: "Guam", fr: "Guam", de: "Guam" },
  { code: "GW", currency: "XOF", nl: "Guinee-Bissau", en: "Guinea-Bissau", fr: "Guinée-Bissau", de: "Guinea-Bissau" },
  { code: "GY", currency: "GYD", nl: "Guyana", en: "Guyana", fr: "Guyana", de: "Guyana" },
  { code: "HK", currency: "HKD", nl: "Hongkong SAR van China", en: "Hong Kong SAR China", fr: "R.A.S. chinoise de Hong Kong", de: "Sonderverwaltungsregion Hongkong" },
  { code: "HM", currency: "AUD", nl: "Heard en McDonaldeilanden", en: "Heard & McDonald Islands", fr: "Îles Heard-et-MacDonald", de: "Heard und McDonaldinseln" },
  { code: "HN", currency: "HNL", nl: "Honduras", en: "Honduras", fr: "Honduras", de: "Honduras" },
  { code: "HR", currency: "EUR", nl: "Kroatië", en: "Croatia", fr: "Croatie", de: "Kroatien" },
  { code: "HT", currency: "HTG", nl: "Haïti", en: "Haiti", fr: "Haïti", de: "Haiti" },
  { code: "HU", currency: "HUF", nl: "Hongarije", en: "Hungary", fr: "Hongrie", de: "Ungarn" },
  { code: "ID", currency: "IDR", nl: "Indonesië", en: "Indonesia", fr: "Indonésie", de: "Indonesien" },
  { code: "IE", currency: "EUR", nl: "Ierland", en: "Ireland", fr: "Irlande", de: "Irland" },
  { code: "IL", currency: "ILS", nl: "Israël", en: "Israel", fr: "Israël", de: "Israel" },
  { code: "IM", currency: "GBP", nl: "Isle of Man", en: "Isle of Man", fr: "Île de Man", de: "Isle of Man" },
  { code: "IN", currency: "INR", nl: "India", en: "India", fr: "Inde", de: "Indien" },
  { code: "IO", currency: "USD", nl: "Brits Indische Oceaanterritorium", en: "British Indian Ocean Territory", fr: "Territoire britannique de l’océan Indien", de: "Britisches Territorium im Indischen Ozean" },
  { code: "IQ", currency: "IQD", nl: "Irak", en: "Iraq", fr: "Irak", de: "Irak" },
  { code: "IR", currency: "IRR", nl: "Iran", en: "Iran", fr: "Iran", de: "Iran" },
  { code: "IS", currency: "ISK", nl: "IJsland", en: "Iceland", fr: "Islande", de: "Island" },
  { code: "IT", currency: "EUR", nl: "Italië", en: "Italy", fr: "Italie", de: "Italien" },
  { code: "JE", currency: "GBP", nl: "Jersey", en: "Jersey", fr: "Jersey", de: "Jersey" },
  { code: "JM", currency: "JMD", nl: "Jamaica", en: "Jamaica", fr: "Jamaïque", de: "Jamaika" },
  { code: "JO", currency: "JOD", nl: "Jordanië", en: "Jordan", fr: "Jordanie", de: "Jordanien" },
  { code: "JP", currency: "JPY", nl: "Japan", en: "Japan", fr: "Japon", de: "Japan" },
  { code: "KE", currency: "KES", nl: "Kenia", en: "Kenya", fr: "Kenya", de: "Kenia" },
  { code: "KG", currency: "KGS", nl: "Kirgizië", en: "Kyrgyzstan", fr: "Kirghizstan", de: "Kirgisistan" },
  { code: "KH", currency: "KHR", nl: "Cambodja", en: "Cambodia", fr: "Cambodge", de: "Kambodscha" },
  { code: "KI", currency: "AUD", nl: "Kiribati", en: "Kiribati", fr: "Kiribati", de: "Kiribati" },
  { code: "KM", currency: "KMF", nl: "Comoren", en: "Comoros", fr: "Comores", de: "Komoren" },
  { code: "KN", currency: "XCD", nl: "Saint Kitts en Nevis", en: "St. Kitts & Nevis", fr: "Saint-Christophe-et-Niévès", de: "St. Kitts und Nevis" },
  { code: "KP", currency: "KPW", nl: "Noord-Korea", en: "North Korea", fr: "Corée du Nord", de: "Nordkorea" },
  { code: "KR", currency: "KRW", nl: "Zuid-Korea", en: "South Korea", fr: "Corée du Sud", de: "Südkorea" },
  { code: "KW", currency: "KWD", nl: "Koeweit", en: "Kuwait", fr: "Koweït", de: "Kuwait" },
  { code: "KY", currency: "KYD", nl: "Kaaimaneilanden", en: "Cayman Islands", fr: "Îles Caïmans", de: "Kaimaninseln" },
  { code: "KZ", currency: "KZT", nl: "Kazachstan", en: "Kazakhstan", fr: "Kazakhstan", de: "Kasachstan" },
  { code: "LA", currency: "LAK", nl: "Laos", en: "Laos", fr: "Laos", de: "Laos" },
  { code: "LB", currency: "LBP", nl: "Libanon", en: "Lebanon", fr: "Liban", de: "Libanon" },
  { code: "LC", currency: "XCD", nl: "Saint Lucia", en: "St. Lucia", fr: "Sainte-Lucie", de: "St. Lucia" },
  { code: "LI", currency: "CHF", nl: "Liechtenstein", en: "Liechtenstein", fr: "Liechtenstein", de: "Liechtenstein" },
  { code: "LK", currency: "LKR", nl: "Sri Lanka", en: "Sri Lanka", fr: "Sri Lanka", de: "Sri Lanka" },
  { code: "LR", currency: "LRD", nl: "Liberia", en: "Liberia", fr: "Liberia", de: "Liberia" },
  { code: "LS", currency: "LSL", nl: "Lesotho", en: "Lesotho", fr: "Lesotho", de: "Lesotho" },
  { code: "LT", currency: "EUR", nl: "Litouwen", en: "Lithuania", fr: "Lituanie", de: "Litauen" },
  { code: "LU", currency: "EUR", nl: "Luxemburg", en: "Luxembourg", fr: "Luxembourg", de: "Luxemburg" },
  { code: "LV", currency: "EUR", nl: "Letland", en: "Latvia", fr: "Lettonie", de: "Lettland" },
  { code: "LY", currency: "LYD", nl: "Libië", en: "Libya", fr: "Libye", de: "Libyen" },
  { code: "MA", currency: "MAD", nl: "Marokko", en: "Morocco", fr: "Maroc", de: "Marokko" },
  { code: "MC", currency: "EUR", nl: "Monaco", en: "Monaco", fr: "Monaco", de: "Monaco" },
  { code: "MD", currency: "MDL", nl: "Moldavië", en: "Moldova", fr: "Moldavie", de: "Republik Moldau" },
  { code: "ME", currency: "EUR", nl: "Montenegro", en: "Montenegro", fr: "Monténégro", de: "Montenegro" },
  { code: "MF", currency: "EUR", nl: "Saint-Martin", en: "St. Martin", fr: "Saint-Martin", de: "St. Martin" },
  { code: "MG", currency: "MGA", nl: "Madagaskar", en: "Madagascar", fr: "Madagascar", de: "Madagaskar" },
  { code: "MH", currency: "USD", nl: "Marshalleilanden", en: "Marshall Islands", fr: "Îles Marshall", de: "Marshallinseln" },
  { code: "MK", currency: "MKD", nl: "Noord-Macedonië", en: "North Macedonia", fr: "Macédoine du Nord", de: "Nordmazedonien" },
  { code: "ML", currency: "XOF", nl: "Mali", en: "Mali", fr: "Mali", de: "Mali" },
  { code: "MM", currency: "MMK", nl: "Myanmar (Birma)", en: "Myanmar (Burma)", fr: "Myanmar (Birmanie)", de: "Myanmar" },
  { code: "MN", currency: "MNT", nl: "Mongolië", en: "Mongolia", fr: "Mongolie", de: "Mongolei" },
  { code: "MO", currency: "MOP", nl: "Macau SAR van China", en: "Macao SAR China", fr: "R.A.S. chinoise de Macao", de: "Sonderverwaltungsregion Macau" },
  { code: "MP", currency: "USD", nl: "Noordelijke Marianen", en: "Northern Mariana Islands", fr: "Îles Mariannes du Nord", de: "Nördliche Marianen" },
  { code: "MQ", currency: "EUR", nl: "Martinique", en: "Martinique", fr: "Martinique", de: "Martinique" },
  { code: "MR", currency: "MRU", nl: "Mauritanië", en: "Mauritania", fr: "Mauritanie", de: "Mauretanien" },
  { code: "MS", currency: "XCD", nl: "Montserrat", en: "Montserrat", fr: "Montserrat", de: "Montserrat" },
  { code: "MT", currency: "EUR", nl: "Malta", en: "Malta", fr: "Malte", de: "Malta" },
  { code: "MU", currency: "MUR", nl: "Mauritius", en: "Mauritius", fr: "Maurice", de: "Mauritius" },
  { code: "MV", currency: "MVR", nl: "Maldiven", en: "Maldives", fr: "Maldives", de: "Malediven" },
  { code: "MW", currency: "MWK", nl: "Malawi", en: "Malawi", fr: "Malawi", de: "Malawi" },
  { code: "MX", currency: "MXN", nl: "Mexico", en: "Mexico", fr: "Mexique", de: "Mexiko" },
  { code: "MY", currency: "MYR", nl: "Maleisië", en: "Malaysia", fr: "Malaisie", de: "Malaysia" },
  { code: "MZ", currency: "MZN", nl: "Mozambique", en: "Mozambique", fr: "Mozambique", de: "Mosambik" },
  { code: "NA", currency: "NAD", nl: "Namibië", en: "Namibia", fr: "Namibie", de: "Namibia" },
  { code: "NC", currency: "XPF", nl: "Nieuw-Caledonië", en: "New Caledonia", fr: "Nouvelle-Calédonie", de: "Neukaledonien" },
  { code: "NE", currency: "XOF", nl: "Niger", en: "Niger", fr: "Niger", de: "Niger" },
  { code: "NF", currency: "AUD", nl: "Norfolk", en: "Norfolk Island", fr: "Île Norfolk", de: "Norfolkinsel" },
  { code: "NG", currency: "NGN", nl: "Nigeria", en: "Nigeria", fr: "Nigeria", de: "Nigeria" },
  { code: "NI", currency: "NIO", nl: "Nicaragua", en: "Nicaragua", fr: "Nicaragua", de: "Nicaragua" },
  { code: "NL", currency: "EUR", nl: "Nederland", en: "Netherlands", fr: "Pays-Bas", de: "Niederlande" },
  { code: "NO", currency: "NOK", nl: "Noorwegen", en: "Norway", fr: "Norvège", de: "Norwegen" },
  { code: "NP", currency: "NPR", nl: "Nepal", en: "Nepal", fr: "Népal", de: "Nepal" },
  { code: "NR", currency: "AUD", nl: "Nauru", en: "Nauru", fr: "Nauru", de: "Nauru" },
  { code: "NU", currency: "NZD", nl: "Niue", en: "Niue", fr: "Niue", de: "Niue" },
  { code: "NZ", currency: "NZD", nl: "Nieuw-Zeeland", en: "New Zealand", fr: "Nouvelle-Zélande", de: "Neuseeland" },
  { code: "OM", currency: "OMR", nl: "Oman", en: "Oman", fr: "Oman", de: "Oman" },
  { code: "PA", currency: "PAB", nl: "Panama", en: "Panama", fr: "Panama", de: "Panama" },
  { code: "PE", currency: "PEN", nl: "Peru", en: "Peru", fr: "Pérou", de: "Peru" },
  { code: "PF", currency: "XPF", nl: "Frans-Polynesië", en: "French Polynesia", fr: "Polynésie française", de: "Französisch-Polynesien" },
  { code: "PG", currency: "PGK", nl: "Papoea-Nieuw-Guinea", en: "Papua New Guinea", fr: "Papouasie-Nouvelle-Guinée", de: "Papua-Neuguinea" },
  { code: "PH", currency: "PHP", nl: "Filipijnen", en: "Philippines", fr: "Philippines", de: "Philippinen" },
  { code: "PK", currency: "PKR", nl: "Pakistan", en: "Pakistan", fr: "Pakistan", de: "Pakistan" },
  { code: "PL", currency: "PLN", nl: "Polen", en: "Poland", fr: "Pologne", de: "Polen" },
  { code: "PM", currency: "EUR", nl: "Saint-Pierre en Miquelon", en: "St. Pierre & Miquelon", fr: "Saint-Pierre-et-Miquelon", de: "St. Pierre und Miquelon" },
  { code: "PN", currency: "NZD", nl: "Pitcairneilanden", en: "Pitcairn Islands", fr: "Îles Pitcairn", de: "Pitcairninseln" },
  { code: "PR", currency: "USD", nl: "Puerto Rico", en: "Puerto Rico", fr: "Porto Rico", de: "Puerto Rico" },
  { code: "PS", currency: "ILS", nl: "Palestijnse gebieden", en: "Palestinian Territories", fr: "Territoires palestiniens", de: "Palästinensische Autonomiegebiete" },
  { code: "PT", currency: "EUR", nl: "Portugal", en: "Portugal", fr: "Portugal", de: "Portugal" },
  { code: "PW", currency: "USD", nl: "Palau", en: "Palau", fr: "Palaos", de: "Palau" },
  { code: "PY", currency: "PYG", nl: "Paraguay", en: "Paraguay", fr: "Paraguay", de: "Paraguay" },
  { code: "QA", currency: "QAR", nl: "Qatar", en: "Qatar", fr: "Qatar", de: "Katar" },
  { code: "RE", currency: "EUR", nl: "Réunion", en: "Réunion", fr: "La Réunion", de: "Réunion" },
  { code: "RO", currency: "RON", nl: "Roemenië", en: "Romania", fr: "Roumanie", de: "Rumänien" },
  { code: "RS", currency: "RSD", nl: "Servië", en: "Serbia", fr: "Serbie", de: "Serbien" },
  { code: "RU", currency: "RUB", nl: "Rusland", en: "Russia", fr: "Russie", de: "Russland" },
  { code: "RW", currency: "RWF", nl: "Rwanda", en: "Rwanda", fr: "Rwanda", de: "Ruanda" },
  { code: "SA", currency: "SAR", nl: "Saoedi-Arabië", en: "Saudi Arabia", fr: "Arabie saoudite", de: "Saudi-Arabien" },
  { code: "SB", currency: "SBD", nl: "Salomonseilanden", en: "Solomon Islands", fr: "Îles Salomon", de: "Salomonen" },
  { code: "SC", currency: "SCR", nl: "Seychellen", en: "Seychelles", fr: "Seychelles", de: "Seychellen" },
  { code: "SD", currency: "SDG", nl: "Soedan", en: "Sudan", fr: "Soudan", de: "Sudan" },
  { code: "SE", currency: "SEK", nl: "Zweden", en: "Sweden", fr: "Suède", de: "Schweden" },
  { code: "SG", currency: "SGD", nl: "Singapore", en: "Singapore", fr: "Singapour", de: "Singapur" },
  { code: "SH", currency: "SHP", nl: "Sint-Helena", en: "St. Helena", fr: "Sainte-Hélène", de: "St. Helena" },
  { code: "SI", currency: "EUR", nl: "Slovenië", en: "Slovenia", fr: "Slovénie", de: "Slowenien" },
  { code: "SJ", currency: "NOK", nl: "Spitsbergen en Jan Mayen", en: "Svalbard & Jan Mayen", fr: "Svalbard et Jan Mayen", de: "Spitzbergen und Jan Mayen" },
  { code: "SK", currency: "EUR", nl: "Slowakije", en: "Slovakia", fr: "Slovaquie", de: "Slowakei" },
  { code: "SL", currency: "SLE", nl: "Sierra Leone", en: "Sierra Leone", fr: "Sierra Leone", de: "Sierra Leone" },
  { code: "SM", currency: "EUR", nl: "San Marino", en: "San Marino", fr: "Saint-Marin", de: "San Marino" },
  { code: "SN", currency: "XOF", nl: "Senegal", en: "Senegal", fr: "Sénégal", de: "Senegal" },
  { code: "SO", currency: "SOS", nl: "Somalië", en: "Somalia", fr: "Somalie", de: "Somalia" },
  { code: "SR", currency: "SRD", nl: "Suriname", en: "Suriname", fr: "Suriname", de: "Suriname" },
  { code: "SS", currency: "SSP", nl: "Zuid-Soedan", en: "South Sudan", fr: "Soudan du Sud", de: "Südsudan" },
  { code: "ST", currency: "STN", nl: "Sao Tomé en Principe", en: "São Tomé & Príncipe", fr: "Sao Tomé-et-Principe", de: "São Tomé und Príncipe" },
  { code: "SV", currency: "USD", nl: "El Salvador", en: "El Salvador", fr: "Salvador", de: "El Salvador" },
  { code: "SX", currency: "XCG", nl: "Sint-Maarten", en: "Sint Maarten", fr: "Saint-Martin (partie néerlandaise)", de: "Sint Maarten" },
  { code: "SY", currency: "SYP", nl: "Syrië", en: "Syria", fr: "Syrie", de: "Syrien" },
  { code: "SZ", currency: "SZL", nl: "Eswatini", en: "Eswatini", fr: "Eswatini", de: "Eswatini" },
  { code: "TC", currency: "USD", nl: "Turks- en Caicoseilanden", en: "Turks & Caicos Islands", fr: "Îles Turques-et-Caïques", de: "Turks- und Caicosinseln" },
  { code: "TD", currency: "XAF", nl: "Tsjaad", en: "Chad", fr: "Tchad", de: "Tschad" },
  { code: "TF", currency: "EUR", nl: "Franse Gebieden in de zuidelijke Indische Oceaan", en: "French Southern Territories", fr: "Terres australes françaises", de: "Französische Süd- und Antarktisgebiete" },
  { code: "TG", currency: "XOF", nl: "Togo", en: "Togo", fr: "Togo", de: "Togo" },
  { code: "TH", currency: "THB", nl: "Thailand", en: "Thailand", fr: "Thaïlande", de: "Thailand" },
  { code: "TJ", currency: "TJS", nl: "Tadzjikistan", en: "Tajikistan", fr: "Tadjikistan", de: "Tadschikistan" },
  { code: "TK", currency: "NZD", nl: "Tokelau", en: "Tokelau", fr: "Tokelau", de: "Tokelau" },
  { code: "TL", currency: "USD", nl: "Oost-Timor", en: "Timor-Leste", fr: "Timor oriental", de: "Timor-Leste" },
  { code: "TM", currency: "TMT", nl: "Turkmenistan", en: "Turkmenistan", fr: "Turkménistan", de: "Turkmenistan" },
  { code: "TN", currency: "TND", nl: "Tunesië", en: "Tunisia", fr: "Tunisie", de: "Tunesien" },
  { code: "TO", currency: "TOP", nl: "Tonga", en: "Tonga", fr: "Tonga", de: "Tonga" },
  { code: "TR", currency: "TRY", nl: "Turkije", en: "Türkiye", fr: "Turquie", de: "Türkei" },
  { code: "TT", currency: "TTD", nl: "Trinidad en Tobago", en: "Trinidad & Tobago", fr: "Trinité-et-Tobago", de: "Trinidad und Tobago" },
  { code: "TV", currency: "AUD", nl: "Tuvalu", en: "Tuvalu", fr: "Tuvalu", de: "Tuvalu" },
  { code: "TW", currency: "TWD", nl: "Taiwan", en: "Taiwan", fr: "Taïwan", de: "Taiwan" },
  { code: "TZ", currency: "TZS", nl: "Tanzania", en: "Tanzania", fr: "Tanzanie", de: "Tansania" },
  { code: "UA", currency: "UAH", nl: "Oekraïne", en: "Ukraine", fr: "Ukraine", de: "Ukraine" },
  { code: "UG", currency: "UGX", nl: "Oeganda", en: "Uganda", fr: "Ouganda", de: "Uganda" },
  { code: "UM", currency: "USD", nl: "Kleine afgelegen eilanden van de Verenigde Staten", en: "U.S. Outlying Islands", fr: "Îles mineures éloignées des États-Unis", de: "Amerikanische Überseeinseln" },
  { code: "US", currency: "USD", nl: "Verenigde Staten", en: "United States", fr: "États-Unis", de: "Vereinigte Staaten" },
  { code: "UY", currency: "UYU", nl: "Uruguay", en: "Uruguay", fr: "Uruguay", de: "Uruguay" },
  { code: "UZ", currency: "UZS", nl: "Oezbekistan", en: "Uzbekistan", fr: "Ouzbékistan", de: "Usbekistan" },
  { code: "VA", currency: "EUR", nl: "Vaticaanstad", en: "Vatican City", fr: "État de la Cité du Vatican", de: "Vatikanstadt" },
  { code: "VC", currency: "XCD", nl: "Saint Vincent en de Grenadines", en: "St. Vincent & Grenadines", fr: "Saint-Vincent-et-les Grenadines", de: "St. Vincent und die Grenadinen" },
  { code: "VE", currency: "VES", nl: "Venezuela", en: "Venezuela", fr: "Venezuela", de: "Venezuela" },
  { code: "VG", currency: "USD", nl: "Britse Maagdeneilanden", en: "British Virgin Islands", fr: "Îles Vierges britanniques", de: "Britische Jungferninseln" },
  { code: "VI", currency: "USD", nl: "Amerikaanse Maagdeneilanden", en: "U.S. Virgin Islands", fr: "Îles Vierges des États-Unis", de: "Amerikanische Jungferninseln" },
  { code: "VN", currency: "VND", nl: "Vietnam", en: "Vietnam", fr: "Viêt Nam", de: "Vietnam" },
  { code: "VU", currency: "VUV", nl: "Vanuatu", en: "Vanuatu", fr: "Vanuatu", de: "Vanuatu" },
  { code: "WF", currency: "XPF", nl: "Wallis en Futuna", en: "Wallis & Futuna", fr: "Wallis-et-Futuna", de: "Wallis und Futuna" },
  { code: "WS", currency: "WST", nl: "Samoa", en: "Samoa", fr: "Samoa", de: "Samoa" },
  { code: "XK", currency: "EUR", nl: "Kosovo", en: "Kosovo", fr: "Kosovo", de: "Kosovo" },
  { code: "YE", currency: "YER", nl: "Jemen", en: "Yemen", fr: "Yémen", de: "Jemen" },
  { code: "YT", currency: "EUR", nl: "Mayotte", en: "Mayotte", fr: "Mayotte", de: "Mayotte" },
  { code: "ZA", currency: "ZAR", nl: "Zuid-Afrika", en: "South Africa", fr: "Afrique du Sud", de: "Südafrika" },
  { code: "ZM", currency: "ZMW", nl: "Zambia", en: "Zambia", fr: "Zambie", de: "Sambia" },
  { code: "ZW", currency: "ZWG", nl: "Zimbabwe", en: "Zimbabwe", fr: "Zimbabwe", de: "Simbabwe" },
];

const BY_CODE = new Map(COUNTRIES.map((c) => [c.code, c]));

export function findCountry(code: string): CountryEntry | undefined {
  return BY_CODE.get((code ?? "").toUpperCase());
}

/** Landnaam in de actieve UI-taal (val terug op Engels). */
export function countryName(code: string, locale: string): string {
  const entry = findCountry(code);
  if (!entry) return code;
  const key = (locale ?? "en").slice(0, 2) as "nl" | "en" | "fr" | "de";
  return entry[key] ?? entry.en;
}

/** Vlagemoji uit de landcode (regional indicator symbols). */
export function flagEmoji(code: string): string {
  const iso = (code ?? "").toUpperCase();
  if (!/^[A-Z]{2}$/.test(iso)) return "\u{1F3F3}";
  return String.fromCodePoint(...[...iso].map((c) => 0x1f1e6 + c.charCodeAt(0) - 65));
}

/** Landen gesorteerd op naam in de gevraagde taal. */
export function sortedCountries(locale: string): CountryEntry[] {
  const key = (locale ?? "en").slice(0, 2) as "nl" | "en" | "fr" | "de";
  const collator = new Intl.Collator(key);
  return [...COUNTRIES].sort((a, b) => collator.compare(a[key] ?? a.en, b[key] ?? b.en));
}
