/**
 * Brevo template audit.
 *
 *   bun run audit:brevo          → prints the resolved mapping + warnings
 *   bun run docs:brevo           → also writes docs/brevo-templates.md
 *
 * It resolves every category × language exactly the way the mailer does at
 * runtime (env overrides included), flags mismatches between the documented
 * scheme and the environment, and reports duplicate/colliding template IDs.
 */

import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import {
  ADMIN_ALERT_TEMPLATE_ID,
  CATEGORY_FALLBACK_OFFSET,
  EMAIL_CATEGORY_BASE,
  EMAIL_LANGUAGES,
  GLOBAL_FALLBACK_TEMPLATE_ID,
  LANGUAGE_OFFSET,
  adminAlertTemplateId,
  brevoTemplateId,
  globalFallbackTemplateId,
  reserveTemplateId,
  type EmailCategory,
  type EmailLanguage,
} from "../src/emails/template-ids";
import { INLINE_ONLY_SENDERS, TEMPLATE_CATALOG } from "../src/emails/template-catalog";

interface Row {
  category: EmailCategory;
  language: EmailLanguage;
  expected: number;
  actual: number;
  source: "scheme" | string;
}

const warnings: string[] = [];
const rows: Row[] = [];

function overrideName(category: EmailCategory, language?: EmailLanguage): string {
  const key = category.toUpperCase();
  return language ? `BREVO_TEMPLATE_${key}_${language.toUpperCase()}` : `BREVO_TEMPLATE_${key}`;
}

for (const entry of TEMPLATE_CATALOG) {
  const base = EMAIL_CATEGORY_BASE[entry.category];
  for (const language of EMAIL_LANGUAGES) {
    const expected = base + LANGUAGE_OFFSET[language];
    const actual = brevoTemplateId(entry.category, language);
    const langVar = overrideName(entry.category, language);
    const catVar = overrideName(entry.category);
    const source =
      actual === expected
        ? "scheme"
        : process.env[langVar]
          ? langVar
          : process.env[catVar]
            ? catVar
            : "UNKNOWN";
    if (source === "UNKNOWN") {
      warnings.push(
        `${entry.category}/${language}: resolved to #${actual} but the scheme expects #${expected} and no env override explains it.`,
      );
    }
    rows.push({ category: entry.category, language, expected, actual, source });
  }
}

// Fallbacks
const fallbackRows = TEMPLATE_CATALOG.map((entry) => {
  const expected = EMAIL_CATEGORY_BASE[entry.category] + CATEGORY_FALLBACK_OFFSET;
  const actual = reserveTemplateId(entry.category);
  const envVar = `BREVO_TEMPLATE_${entry.category.toUpperCase()}_FALLBACK`;
  return { category: entry.category, expected, actual, override: process.env[envVar] ? envVar : "—" };
});

const adminAlert = adminAlertTemplateId();
const globalFallback = globalFallbackTemplateId();
if (adminAlert !== ADMIN_ALERT_TEMPLATE_ID)
  warnings.push(`Admin alert template overridden to #${adminAlert} (default #${ADMIN_ALERT_TEMPLATE_ID}).`);
if (globalFallback !== GLOBAL_FALLBACK_TEMPLATE_ID)
  warnings.push(
    `Global fallback template overridden to #${globalFallback} (default #${GLOBAL_FALLBACK_TEMPLATE_ID}).`,
  );

// Collision check: two *distinct* categories resolving to the same ID is only
// expected inside the shared auth block (base 12).
const byId = new Map<number, Set<string>>();
for (const row of rows) {
  const set = byId.get(row.actual) ?? new Set<string>();
  set.add(`${row.category}/${row.language}`);
  byId.set(row.actual, set);
}
for (const [id, users] of byId) {
  const bases = new Set([...users].map((u) => EMAIL_CATEGORY_BASE[u.split("/")[0] as EmailCategory]));
  if (users.size > 1 && bases.size > 1) {
    warnings.push(`Template #${id} is shared by different blocks: ${[...users].join(", ")}`);
  }
}

// Stray env overrides that point at a category we do not know.
const knownPrefixes = new Set(TEMPLATE_CATALOG.map((e) => `BREVO_TEMPLATE_${e.category.toUpperCase()}`));
for (const name of Object.keys(process.env)) {
  if (!name.startsWith("BREVO_TEMPLATE_")) continue;
  if (name === "BREVO_TEMPLATE_ADMIN_ALERT" || name === "BREVO_TEMPLATE_GLOBAL_FALLBACK") continue;
  const matches = [...knownPrefixes].some((p) => name === p || name.startsWith(`${p}_`));
  if (!matches) warnings.push(`Unknown env override "${name}" — no matching category.`);
}

// ---------------------------------------------------------------- reporting
const langHeader = EMAIL_LANGUAGES.join(" | ");

function markdown(): string {
  const lines: string[] = [];
  lines.push("# ROUT — Brevo template mapping");
  lines.push("");
  lines.push("_Generated by `bun run docs:brevo` from src/emails/template-ids.ts and template-catalog.ts. Do not edit by hand._");
  lines.push("");
  lines.push("## Numbering scheme");
  lines.push("");
  lines.push("Each category owns a contiguous block of Brevo IDs:");
  lines.push("");
  lines.push("```text");
  lines.push("template id = category base + language offset");
  lines.push("category fallback = category base + 9");
  lines.push("```");
  lines.push("");
  lines.push("| Language | Offset |");
  lines.push("| --- | --- |");
  for (const lang of EMAIL_LANGUAGES) lines.push(`| ${lang} | +${LANGUAGE_OFFSET[lang]} |`);
  lines.push(`| _category fallback_ | +${CATEGORY_FALLBACK_OFFSET} |`);
  lines.push("");
  lines.push("## Delivery cascade");
  lines.push("");
  lines.push("1. Target template — category base + language offset");
  lines.push(`2. Category fallback — category base + ${CATEGORY_FALLBACK_OFFSET}`);
  lines.push(`3. Global fallback — #${globalFallback}`);
  lines.push("4. Inline HTML rendered by ROUT itself");
  lines.push("");
  lines.push(`Every downgrade triggers the admin alert template #${adminAlert}.`);
  lines.push("");
  lines.push("## Resolved template IDs");
  lines.push("");
  lines.push(`| Category | Base | ${langHeader} | Fallback |`);
  lines.push(`| --- | --- | ${EMAIL_LANGUAGES.map(() => "---").join(" | ")} | --- |`);
  for (const entry of TEMPLATE_CATALOG) {
    const cells = EMAIL_LANGUAGES.map(
      (lang) => rows.find((r) => r.category === entry.category && r.language === lang)!.actual,
    );
    const fb = fallbackRows.find((f) => f.category === entry.category)!.actual;
    lines.push(
      `| ${entry.category} | ${EMAIL_CATEGORY_BASE[entry.category]} | ${cells.join(" | ")} | ${fb} |`,
    );
  }
  lines.push("");
  lines.push("## Categories, senders and params");
  lines.push("");
  for (const entry of TEMPLATE_CATALOG) {
    lines.push(`### ${entry.label} (\`${entry.category}\`)`);
    lines.push("");
    lines.push(`- Base ID: **${EMAIL_CATEGORY_BASE[entry.category]}**`);
    lines.push(`- Sent from: ${entry.senders.map((s) => `\`${s}\``).join(", ")}`);
    lines.push(`- Params: ${entry.params.map((p) => `\`{{ params.${p} }}\``).join(", ")}`);
    lines.push("");
  }
  lines.push("## Inline-only mails (no Brevo template)");
  lines.push("");
  for (const s of INLINE_ONLY_SENDERS) lines.push(`- \`${s}\``);
  lines.push("");
  lines.push("## Environment overrides");
  lines.push("");
  lines.push("| Variable | Effect |");
  lines.push("| --- | --- |");
  lines.push("| `BREVO_API_KEY` | Required. Without it no mail is sent. |");
  lines.push("| `BREVO_SENDER_EMAIL` / `BREVO_SENDER_NAME` | Visible sender. |");
  lines.push("| `BREVO_REPLY_TO_EMAIL` | Reply-to address. |");
  lines.push("| `CONTACT_ADMIN_EMAIL` | Recipient of admin alerts. |");
  for (const entry of TEMPLATE_CATALOG) {
    const key = entry.category.toUpperCase();
    lines.push(`| \`BREVO_TEMPLATE_${key}_<LANG>\` | Overrides one language of \`${entry.category}\`. |`);
    lines.push(`| \`BREVO_TEMPLATE_${key}\` | Overrides all languages of \`${entry.category}\`. |`);
    lines.push(`| \`BREVO_TEMPLATE_${key}_FALLBACK\` | Overrides the category fallback. |`);
  }
  lines.push(`| \`BREVO_TEMPLATE_ADMIN_ALERT\` | Admin alert template (default #${ADMIN_ALERT_TEMPLATE_ID}). |`);
  lines.push(
    `| \`BREVO_TEMPLATE_GLOBAL_FALLBACK\` | Global reserve template (default #${GLOBAL_FALLBACK_TEMPLATE_ID}). |`,
  );
  lines.push("");
  lines.push("## Audit result");
  lines.push("");
  if (warnings.length === 0) lines.push("No mismatches: every resolved ID matches the documented scheme.");
  else for (const w of warnings) lines.push(`- ${w}`);
  lines.push("");
  return lines.join("\n");
}

const write = process.argv.includes("--write");
const doc = markdown();

if (write) {
  const target = resolve(import.meta.dirname ?? ".", "../docs/brevo-templates.md");
  mkdirSync(dirname(target), { recursive: true });
  writeFileSync(target, doc, "utf8");
  console.info(`[brevo-audit] wrote ${target}`);
}

console.info(doc);
console.info(
  warnings.length === 0
    ? "\n[brevo-audit] OK — resolved IDs match the scheme and env overrides."
    : `\n[brevo-audit] ${warnings.length} warning(s) — see above.`,
);
process.exit(warnings.length === 0 ? 0 : 1);
